### ISSUE TITLE
Where to store config file?

### ISSUE THREAD

**Issue by vinliao** [fiatjaf/noscl#18]
I'm building a Rust CLI client (https://github.com/vinliao/clust). I took some inspiration and ideas from `noscl` (thank you very much). I'm still confused where to place the config file, which contains private-key and a list of relays. 

I haven't tried `noscl`. Where does it store config file? Is the config file json, or an rc file (like `.vimrc`)? Is storing private-key in a plaintext, placed in `$HOME` safe enough?

**Comment by honza** [comment]
By default, it's `~/.config/nostr/config.json`. Have a look [here](https://github.com/fiatjaf/noscl/blob/master/main.go#L38).

**Comment by vinliao** [comment]
Ah, I didn't see that particular line of code. Thanks. What about Windows?
