### ISSUE TITLE
"key too short was 63 characters, must be 32 bytes hex-encoded, i.e. 64 characters“

### ISSUE THREAD

**Issue by imherenews** [fiatjaf/noscl#29]
I got this error with running `noscl setprivate xxxxxx" , the key is my private key copied from astral. Any clue? 

`<> 2023/01/09 23:52:12 key too short was 63 characters, must be 32 bytes hex-encoded, i.e. 64 characters.`

**Comment by fiatjaf** [comment]
Prefix it with a zero.

**Comment by imherenews** [comment]
hmm, it says another issue:
`<> 2023/01/10 09:11:55 Error decoding key from hex: encoding/hex: invalid byte: U+006E 'n'`

**Comment by fiatjaf** [comment]
Oh, you're pasting a bech32 key. noscl only accepts hex keys. Please send a PR fixing that. Or use https://damus.io/key.
