### ISSUE TITLE
Weird "noscl public" output

### ISSUE THREAD

**Issue by gourcetools** [fiatjaf/noscl#33]
The output of noscl public should be:

> 0000005cc4586681ad8e7f4b75436fb7904b0e34ff072bb3406ddb90226d7eab

but its:

> 5cc4586681ad8e7f4b75436fb7904b0e34ff072bb3406ddb90226d7eab

![image](https://user-images.githubusercontent.com/120996278/213589213-fba16adb-dcc4-402c-bf65-3069d353c9e4.png)

I gues this makes my publish command fails ( i tried other keys and its working... but not this one) 

![image](https://user-images.githubusercontent.com/120996278/213589463-3388d508-69ca-43aa-b362-57d785c318d5.png)
https://www.nostr.guru/e/138b088388ddaf56c78c5f798c118a92e63fff6850280d5d1d3b8d76542b2225

**Comment by fiatjaf** [comment]
Hmm, it should be padding with zeroes.

**Comment by gourcetools** [comment]
Hmmmm... i had multiple private keys assigned. Sorry. Must by bad usage on my end...

**Comment by gourcetools** [comment]
I think i made it buggy by abusing it... if you want i can document this more but im no expert.

**Comment by fiatjaf** [comment]
No, it is a bug indeed. Must be fixed.

**Comment by jeremyd** [comment]
noscl setprivate
noscl public (outputs wrong pubkeys).

this seemed to work for my previous key but not for this new 32bit POW key?

Hm.

**Comment by gourcetools** [comment]
👏
