### ISSUE TITLE
I want to show my follow list

### ISSUE THREAD

**Issue by amandafanny** [fiatjaf/noscl#38]
when I follow many people, I don't know my follow list.

<img width="387" alt="image" src="https://user-images.githubusercontent.com/54808661/217744641-515ea8c7-210c-43be-8dad-499ba9a43527.png">
add follow people doesn't have any verification.
<img width="564" alt="image" src="https://user-images.githubusercontent.com/54808661/217744424-38ab75e9-2198-404c-ade9-0b3fa056930a.png">

**Comment by honza** [comment]
Done in 3a7a96894fdfa71699d713370074aabc974c20e0
