### ISSUE TITLE
No included way to generate a private key

### ISSUE THREAD

**Issue by Koshroy** [fiatjaf/noscl#6]
Right now `noscl` lets you set a private key using "setprivate", but offers no option to generate a private key for you. Is this something you'd be interested in having `noscl` support? I can submit a PR for that.

**Comment by fiatjaf** [comment]
Yes, if you use the scheme from: https://github.com/fiatjaf/nostr/blob/master/nips/06.md

Actually I think it's better to create a subdirectory/subpackage on github.com/fiatjaf/go-nostr called `nip06` and implement this there, then import the functions here.

**Comment by Koshroy** [comment]
Sure I'll take a stab at attempting this in go-nostr then call them here.
